### PR TITLE
Added availability through nix to the readme

### PR DESCRIPTION
**Pull request by mgttlinger**
Given that I have written a nix derivation for inboxer a while ago, which now is included in the stable channel, I thought it would be a good addition to the README

### CODE REVIEW

**Comment by denysdovhan** [comment]
@JohnnyBui ?

**Comment by johnnybui** [comment]
@mgttlinger can you make it always link the latest version?

**Comment by mgttlinger** [comment]
It links to the search query and hence to the latest version in the stable channel indexed by the search. Or did I misunderstand the question?

**Comment by johnnybui** [comment]
I asked because I checked https://nixos.org/nixos/packages.html#inboxer and saw version 1.0.2 while the latest version of Inboxer is 1.1.2

**Comment by mgttlinger** [comment]
Ah, yes we have a semi automated update process in place and the [current version in master](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/mailreaders/inboxer/default.nix) is 1.1.2 but it takes time to propagate those changes to the stable channel and thereby also the index.
A user can however choose to use the unstable channel which usually has the changes of master within a few days.

**Comment by johnnybui** [comment]
Cool. Good work and thanks for the info!

**Pull request merged**
