### PR TITLE
(fix) error when launching on macOS with disabled show unread badge

### PR DESCRIPTION
**Pull request by johnnybui**

### CODE REVIEW

**Review by denysdovhan — APPROVED** [review]

**Comment by denysdovhan** [comment]
@JohnnyBui feel free to merge and release new version.

**Comment by johnnybui** [comment]
@denysdovhan I cannot pumb new version to master (package.json)

**Comment by denysdovhan** [comment]
@JohnnyBui use this release checklist:

1) Draft a new release at [Releases](https://github.com/denysdovhan/inboxer/releases) page
2) Pull all changes locally
3) Run `npm version patch`, `npm version minor` or `npm version major` to bump a version and create a tag
4) Push all changes with `git push --follow-tags`
5) Publish a release created at step 1

After passing a CI, all compiled binaries will be attached to the drafted release. 

You can also check [Recommended GitHub Releases Workflow](https://www.electron.build/configuration/publish#recommended-github-releases-workflow)

**Comment by JohnnyBui** [comment]
Cool. Thanks

**Comment by johnnybui** [comment]
When I do step 4, it says `! [remote rejected] master -> master (protected branch hook declined)`

**Comment by denysdovhan** [comment]
@JohnnyBui strange. `master` branch is protected. The rejection might happen because of force push.

**Comment by johnnybui** [comment]
@denysdovhan Do I need additional permission to push changes to master this case?

**Comment by denysdovhan** [comment]
@JohnnyBui nope, you don't. I should work for you.

**Pull request merged**
