### PR TITLE
replace deprecated method app.makeSingleInstance

### PR DESCRIPTION
**Pull request by jmarino**
Electron-3.x changes the way to do single instance and deprecates the old way. After upgrade from electron-2.x we get the following warning on startup:
`(electron) 'app.makeSingleInstance(cb)' is deprecated. Use 'app.requestSingleInstanceLock() and app.on('second-instance', cb)' instead.`

In the electron docs they give an example of how to use the new way of handling single instance:
https://electronjs.org/docs/all#apprequestsingleinstancelock

### CODE REVIEW

**Comment by jmarino** [comment]
Maybe I was premature with this pull request. The Travis build system seems to use electron-2.x. Is this requested in `package.json`?

Anyway, fell free to dismiss this pull request.

**Comment by denysdovhan** [comment]
Please, make CI green.

**Comment by jmarino** [comment]
I am unable to fix the Travis CI issues. I've been tinkering with this branch to see if I could make it happy without success. I've even reverted all changes to match branch master and Travis CI still fails. The Travis build issues seem to have nothing to do with my changes.

With all code reverted to match master Travis CI fails with:
`At least electron-updater 4.0.0 is recommended by current electron-builder version. Please set electron-updater version to "^4.0.0"`

After setting electron-updater version to 4.0.0 it fails during windows build:
`error output:wine: failed to initialize: dlopen(/tmp/wine-stage/wine/usr/lib/wine/ntdll.dll.so, 258): image not found`

This looks like an issue with electron-builder which downloads `wine-2.0.3-mac-10.13` during the windows build. This binary was released over a year ago. Looking in the `electron-builder-binaries` repo I see that the latest release is [`wine-3.0.3-mac-10.13`](https://github.com/electron-userland/electron-builder-binaries/releases).

**Comment by jmarino** [comment]
I was finally able to fix the travis build. The fix required updating the node version used by travis, updating the mac container to xcode10 as suggested [here](https://github.com/electron-userland/electron-builder/issues/3562#issuecomment-450434757), and updating the dependencies to more current versions.

I apologize for all the git churn while I debugged the issue. I have done a final rebase and force push to leave things as clean as possible.

**Comment by denysdovhan** [comment]
Thanks!

**Pull request merged**
